server:
  port: 1022

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true  #取消控制台懒加载，默认false要刷新请求才会在面板显示

management:
  endpoints:
    web:
      exposure:
        include: "*"

#服务降级配置:开启sentinel
feign:
  sentinel:
    enabled: true


#nacos-provider: #服务名
#  ribbon:
#    NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #轮询